package com.swedaiaiwallpapersart.backgroundanimewallpaperaiphoto.generateImages.models

data class PostRequestModelIG(
    var canvasPos: Int? = null,
    var endpoint: String? = null,
    var enhance_prompt: String? = null,
    var exact_Nprompt: String? = null,
    var guess_mode: String? = null,
    var guidance_scale: Double? = null,
    var height: String? = null,
    var instance_prompt: String? = null,
    var key: String? = null,
    var model_id: String? = null,
    var model_name: String? = null,
    var multi_lingual: String? = null,
    var negative_prompt: String? = null,
    var num_inference_steps: String? = null,
    var panorama: String? = null,
    var prompt: String? = null,
    var promptsBuilder: String? = null,
    var safety_checker: String? = null,
    var samples: String? = null,
    var scheduler: String? = null,
    var self_attention: String? = null,
    var steps: String? = null,
    var strength: Double? = null,
    var token: String? = null,
    var type: String? = null,
    var upscale: String? = null,
    var webhook: String? = null,
    var width: String? = null
)
